---
title: "EDMA form matrix"
author: "Peter Solymos"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{EDMA form matrix}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
set.seed(429)
```

The nonparametric estimator gives the mean form matrix ($\hat{M}$)
and $\hat{\Sigma}_{K}^\ast$, that we can extract from the fitted
model object `fit` using the `Meanform` and `SigmaKstar` functions:

```{r fit}
library(EDMAinR)
file <- system.file("extdata/crouzon/Crouzon_P0_Global_MUT.xyz", 
    package="EDMAinR")
x <- read_xyz(file)

fit <- edma_fit(x, B=9)
fit

str(Meanform(fit))
str(SigmaKstar(fit))
```

We can extract stacked Euclidean distances with the `get_fm` function:

```{r stackeddist}
head(get_fm(fit))
head(get_fm(fit, sort=TRUE, decreasing=TRUE))
head(get_fm(fit, sort=TRUE, decreasing=FALSE))
```

The 2D plot gives the projection of the mean form,
dot size proportional to SigmaKstar diagonal elements:

```{r fig.width=7,fig.height=5,out.width='60%'}
plot_2d(fit)
```

```{r fig.width=7,fig.height=5,out.width='100%'}
library(rgl)
plot_3d(fit)
rglwidget(width = 600, height = 600, reuse = FALSE)
```

